name: Scheduled Update Issue Classification

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-classification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install @octokit/graphql

    - name: Calculate and Update Classification
      run: node update-classification.mjs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
